from typing import Annotated, Literal, Optional
from pydantic import BaseModel, Field
from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages


class AgentSchema(BaseModel):
    """Shared state for the SQL agent graph."""

    messages: Annotated[list[BaseMessage], add_messages] = Field(
        default_factory=list,
        description="Conversation history with the agent.",
    )
    user_input: str = Field(..., description="The user's original question.")
    curated_query: str = Field(default="", description="The curated question for SQL generation.")
    prompt_query_context: str = Field(default="", description="Full prompt with schema context for the LLM.")
    generated_sql_query: str = Field(default="", description="The SQL generated by the agent.")
    is_safe: Literal["Yes", "No"] = Field(default="No", description="Whether the SQL is safe to execute.")
    comments: str = Field(default="", description="Judge's reasoning about the safety of the SQL.")
    sql_query_execution_result: Optional[str] = Field(default=None, description="Result of executing the SQL.")
    final_response: Optional[str] = Field(default=None, description="Final user-facing answer.")


class JudgeSchema(BaseModel):
    """Structured output for the SQL safety judge."""

    answer: Literal["Yes", "No"] = Field(..., description="'Yes' if safe, 'No' otherwise.")
    comments: str = Field(..., description="Reasoning for the judge's decision.")