[project]
name = "data-agent-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Yanglesh5139", email = "88960301+Yanglesh5139@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "ipython>=9.17.1",
    "langchain>=1.4.3",
    "langchain-openai>=1.6.7",
    "langgraph>=1.2.12",
    "psycopg2-binary>=2.9.13",
    "pydantic>=2.13.5",
]

[project.scripts]
data-agent-project = "data_agent_project:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
