# from pydantic import BaseModel, Field
# from typing import Annotated,Literal
# from operator import add

# class AgentSchema(BaseModel):
#     messages: Annotated[list,add]= Field(..., description="List of messages exchanged with the agent.")
#     user_input: str = Field(..., description="The question provided by the user to the agent.")
#     curated_query: Annotated[str,add] = Field(..., description="The curated query generated by the agent.")
#     prompt_query_context: str= Field(..., description="A detailed prompt with SQL DB context that will help agent to generate SQL query.") 
#     generated_sql_query: str = Field(..., description="The SQL query generated by the agent based on the curated query and prompt context.")
#     is_safe: Literal["Yes", "No"] = Field(..., description="Indicates whether the generated SQL query is safe to execute or not.")
#     comments: str=Field(...,description="Comments regarding the safety of the generated sql query")
#     sql_query_execution_result: str = Field(..., description="The result of executing the generated SQL query.")
#     final_response: str = Field(..., description="The final response generated by the agent after processing the SQL query execution result.")

# class JudgeSchema(BaseModel):
#     answer: Literal["Yes","No"]=Field(..., description="Indicates whether the generated SQL query is safe to execute or not")
#     comments: str=Field(...,description="Additional comments or feedback from the judge regarding the SQL query")

from typing import Annotated, Literal, Optional
from pydantic import BaseModel, Field
from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages


class AgentSchema(BaseModel):
    """Shared state for the SQL agent graph."""

    messages: Annotated[list[BaseMessage], add_messages] = Field(
        default_factory=list,
        description="Conversation history with the agent.",
    )
    user_input: str = Field(..., description="The user's original question.")
    curated_query: str = Field(default="", description="The curated question for SQL generation.")
    prompt_query_context: str = Field(default="", description="Full prompt with schema context for the LLM.")
    generated_sql_query: str = Field(default="", description="The SQL generated by the agent.")
    is_safe: Literal["Yes", "No"] = Field(default="No", description="Whether the SQL is safe to execute.")
    comments: str = Field(default="", description="Judge's reasoning about the safety of the SQL.")
    sql_query_execution_result: Optional[str] = Field(default=None, description="Result of executing the SQL.")
    final_response: Optional[str] = Field(default=None, description="Final user-facing answer.")


class JudgeSchema(BaseModel):
    """Structured output for the SQL safety judge."""

    answer: Literal["Yes", "No"] = Field(..., description="'Yes' if safe, 'No' otherwise.")
    comments: str = Field(..., description="Reasoning for the judge's decision.")